name: Deploy Yokun frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Yokun frontend
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy files to server
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIR }}
